apiVersion: v1
kind: Service
metadata:
  name: java-hello
spec:
  selector:
    app: java-hello
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
