apiVersion: v1
kind: Service
metadata:
  name: angular-hello
spec:
  selector:
    app: angular-hello
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
